### ISSUE TITLE
performance questions

### ISSUE THREAD

**Issue by jangorecki** [cbailiss/pivottabler#44]
Thanks for this package. I was waiting long time for such functionality. I haven't spent much yet reading the documentation, but got some questions.

- Looking at http://www.pivottabler.org.uk/articles/v11-performance.html I see some timings that are coming batch vs sequential mode. What are `batch` sizes there? is it possible to control batch size? What will be the timing if the batch size will be equal to result size, so there will be only single batch?

- Is you package in any way using data.table's `groupingsets`, `rollup` or `cube`? They seems to be perfect fit fot your use case. They cannot reshape, but they calculate subtotals on many levels at once, and a grand total.

- Is your package using data.table's dcast or melt for reshaping data to pivot form?

- Is there any support for reactivity? could be even just a javascript side reactivity, so all computation  in R could be pre-computed, and the javascript could interactively access those pre-computed pivot tables.

**Comment by cbailiss** [comment]
> What are batch sizes there? is it possible to control batch size? What will be the timing if the batch size will be equal to result size, so there will be only single batch?

Batches are determined by the shape of the data, rather than sizes.  Aggregations on different variable combinations will generate different batches, e.g. 
`pt$showBatchInfo()`
```
BATCH 1: DATA: bhmtrains, 2 VARS: [TOC, TrainCategory]
BATCH 2: DATA: bhmtrains, 1 VAR: [TOC]
BATCH 3: DATA: bhmtrains, 1 VAR: [TrainCategory]
BATCH 4: DATA: bhmtrains, 0 VARS: []
```
The benefit of the batching is that one batch might cover 100 cells in a pivot table, so a computation only needs to be done once, rather than one computation execution per cell.

> Is you package in any way using data.table's groupingsets, rollup or cube? They seems to be perfect fit fot your use case.

The package only uses basic data.table subset-calculate-group functionality (aka. `DT[i, j, by]`).  groupingsets, rollup, cube, etc are interesting functions that offer some optimisation opportunities for the future, but aren't used currently.

> Is your package using data.table's dcast or melt for reshaping data to pivot form?

No

>Is there any support for reactivity?

No, though the package can be used with shiny.

**Comment by jangorecki** [comment]
OK, thank you for your answers. I am fine to close this issue.
