### ISSUE TITLE
Is there an option to replace missing value with character like "-"

### ISSUE THREAD

**Issue by meichan1128** [cbailiss/pivottabler#58]
My table is created by: 
pt$addColumnDataGroups
pt$addRowDataGroups
pt$defineCalculation (using summariseExpression = sum(value))

There are some missing values in the table and I'd like to replace them with "-"
I wonder how to do it.

**Comment by cbailiss** [comment]
**Summary**

There are two different options - depending on the scenario you have:

1. If the data group combination has no matching rows in the data frame, use the noDataCaption argument.
2. If rows do exist for the data group combination in the data frame but the values are NA, use the exportOptions argument.

**Option 1 - noDataCaption**

Use the `noDataCaption` argument of the `defineCalculation()` function.

More information:
http://pivottabler.org.uk/articles/v03-calculations.html#empty-cells-1

In the example below, there are no "Ordinary Passenger" trains for "Virgin Trains" in the `bhmtrains` data frame.  In example 2, the empty cell is changed to display a dash.

```
library(pivottabler)

# example 1 - normal output
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()

# example 2 - change NA to dash
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()", noDataCaption="-")
pt$renderPivot()
```

![image](https://user-images.githubusercontent.com/11745789/105626518-0c1f1b00-5e28-11eb-874e-f321d8bac833.png)

**Option 2 - exportOptions**

Use the `exportOptions` argument of `pt$renderPivot()` function.

In the code below, example 1 is the normal output and example 2 changes the NAs to dash.

More information:
http://pivottabler.org.uk/articles/vA1-appendix.html#output-of-na-nan-inf-and-inf

In the example below, there is a row for the colour "Green" in the data frame, but it has value NA.  In example 2, a dash is output instead of NA for the colour "Green".

```
library(pivottabler)

someData <- data.frame(Colour=c("Red", "Yellow", "Green", "Blue", "White", "Black"),
                       SomeNumber=c(1, 2, NA, NaN, -Inf, Inf))

# example 1 - normal output
pt <- PivotTable$new()
pt$addData(someData)
pt$addRowDataGroups("Colour")
pt$defineCalculation(calculationName="Total", summariseExpression="sum(SomeNumber)")
pt$evaluatePivot()
pt$renderPivot()

# example 2 - change NA to dash
pt <- PivotTable$new()
pt$addData(someData)
pt$addRowDataGroups("Colour")
pt$defineCalculation(calculationName="Total", summariseExpression="sum(SomeNumber)")
pt$evaluatePivot()
pt$renderPivot(exportOptions=list(exportNAAs="-"))
```

![image](https://user-images.githubusercontent.com/11745789/105626142-f6105b00-5e25-11eb-9b20-f519cd089b63.png)
