### ISSUE TITLE
Approach to speed up the process while rendering the pivot tabler and also writing it to worksheet

### ISSUE THREAD

**Issue by meichan1128** [cbailiss/pivottabler#60]
My pivot table consists of more than 10k rows and 10 columns, 
1 rowDataGroups and 1 columnGroup and 1 columnDataGroups were added :
I was trying to use 
pt$renderPivot() to render my table

and hence to use
pt$renderwriteToWorksheet()
to export my pivot table in xlsx formatted with styling.

However both of two steps took ages correspondingly to complete (the rendering took nearly an hour and writeToWorksheet took few hours to the completion). I wonder if there is any faster option. I have already switch to data.table as my processing library. Thank you so much.

**Comment by cbailiss** [comment]
Unfortunately there is no way to make this dramatically quicker and have all the same functionality.  
A pivot table with 100000 cells is a large pivot table and will take time to generate and export.

Switching the argumentCheckMode to NONE can help to reduce the pivot table calculation time - but the reduction will not be huge.
`pt <- PivotTable$new(argumentCheckMode="NONE")`

If you are only generating the pivot table for Excel, then there is no need to call pt$renderPivot() as well - just use:
```
pt$evaluatePivot()
pt$writeToExcelWorksheet()
```
This saves a little time by not generating the HTML version.

Exporting to Excel is slow mainly because of the formatting/styling.  If you don't need this it can be disabled using:
`pt$writeToExcelWorksheet(applyStyles=TRUE)`

**Comment by cbailiss** [comment]
Just corrected a typo:  The last line should be:  `pt$writeToExcelWorksheet(applyStyles=FALSE)`

**Comment by meichan1128** [comment]
Thank you for your reply. I might go for the option of turning the styling off.

**Comment by cbailiss** [comment]
The only other option would be to use more primitive/optimised data structures (e.g. data frames, tibbles, data.table) instead of pivottabler.  You will probably need to write more code to produce the output, but you can optimise the processing directly.

**Comment by meichan1128** [comment]
Do you mean that instead of using pivottabler package, the only faster way is to compute the expected result directly by writing my own codes and adjust the styling via package like basictabler. I might consider that too.

**Comment by cbailiss** [comment]
Yes.
