### ISSUE TITLE
knitr 1.13 doesn't detect pivottabler output as html

### ISSUE THREAD

**Issue by robsalasco** [cbailiss/pivottabler#8]
Hi! found a bug in the output of the package. To fix the issue I have to use the option `screenshot.force = FALSE`.

```
---
title: "Example"
author: "Example"
date: "`r Sys.Date()`"
output: html_document
---
  

```{r, message=FALSE, warning=FALSE, screenshot.force = FALSE }
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
```
```

**Comment by cbailiss** [comment]
Hi there

1.13 is quite an old version of knitr (from May 2016).  Is is possible to upgrade to the current version (1.18) and retest?  Or are you restricted to the older version due to some other reason?  What output are you seeing?

Testing with the current version in R Studio gives the results shown in the attached image.

![example](https://user-images.githubusercontent.com/11745789/34654599-095e19d8-f3f6-11e7-9a0a-0d4ea6efa56b.png)

Chris

**Comment by robsalasco** [comment]
Hi @cbailiss,

I was using 1.17, with the new version now is working as expected.

Thank you!
